version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - ecommerce

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - RAZORPAY_KEY=your_key
      - RAZORPAY_SECRET=your_secret
    depends_on:
      - mongo
    networks:
      - ecommerce

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce

  nginx:
    build:
      context: ./frontend
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce

volumes:
  mongo_data:

networks:
  ecommerce:

