version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecommerce

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - RAZORPAY_KEY=your_key
      - RAZORPAY_SECRET=your_secret
    depends_on:
      - mongo
    networks:
      - ecommerce

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce

volumes:
  mongo_data:

networks:
  ecommerce:

